name: TrMenu Dev

on:
  push:
  pull_request:

jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: set up JDK 8
        uses: actions/setup-java@main
        with:
          java-version: 8
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./*
